apiVersion: v1
kind: Service
metadata:
  name: appflowy-service
  namespace: appflowy
spec:
  selector:
    app: appflowy
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
